[shell]
program = "/bin/zsh"

[window]
title = "Terminal"
class.general = "Alacritty"
# dimensions = { columns = 30, lines = 30 }
dimensions.columns = 96
dimensions.lines = 48
opacity = 0.9

[scrolling]
multiplier = 5

[font]
# FontManager: Font -> Properties -> Family
normal.family = "JetBrainsMonoNL Nerd Font Mono"
normal.style = "Medium"
bold.family = "JetBrainsMonoNL Nerd Font Mono"
bold.style = "ExtraBold"
italic.family = "JetBrainsMonoNL Nerd Font Mono"
italic.style = "Medium Italic"
bold_italic.family = "JetBrainsMonoNL Nerd Font Mono"
bold_italic.style = "ExtraBold Italic"
size = 11.75

[selection]
# Consider adding - and/or _
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t/"

[cursor]
style.shape = "Beam"
# style.blinking = "On"
# blink_timeout = 0
unfocused_hollow = false
thickness = 0.25
