# sys-auth/pam-sleep

# TODO: Very rough ebuild for now, I wanted this to be handled by portage, but
# currently have a lot on my plate and didn't really polish this as much as I
# should have.
#
# One such example is the name. The repo and the executable are different names
# because I'm particular about my project naming for github. This is probably
# not ideal, but again, good enough for my personal use.

EAPI=8

# Generated by pycargoebuild -- A lot of these sorta came "out of the box" when
# I started building this, and I don't yet know rust/cargo well enough to make
# a good guess what the implications of all of them are. Alas, it may be
# possible to prune these, but this is good enough to get started.
CRATES="
	aho-corasick@1.1.5
	bindgen@0.69.5
	bitflags@1.3.2
	bitflags@2.13.1
	cexpr@0.6.0
	cfg-if@1.0.4
	cfg_aliases@0.2.2
	clang-sys@1.9.1
	either@1.17.0
	enum-repr@0.2.6
	glob@0.3.4
	itertools@0.12.1
	itoa@1.0.18
	lazy_static@1.5.0
	lazycell@1.3.0
	libc@0.2.189
	log@0.4.33
	memchr@2.8.3
	minimal-lexical@0.2.1
	nix@0.29.0
	nom@7.1.3
	pam-client@0.5.0
	pam-sys@1.0.0-alpha5
	proc-macro2@1.0.107
	quote@1.0.47
	regex-automata@0.4.18
	regex-syntax@0.8.11
	regex@1.13.1
	rpassword@6.0.1
	rustc-hash@1.1.0
	rustversion@1.0.23
	serde@1.0.229
	serde_core@1.0.229
	serde_derive@1.0.229
	serde_json@1.0.151
	shlex@1.3.0
	syn@1.0.109
	syn@2.0.119
	syn@3.0.3
	unicode-ident@1.0.24
	users@0.11.0
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	zmij@1.0.23
"

inherit cargo
inherit git-r3

DESCRIPTION="Provides the power-state utility for suspend via PAM authentication."
HOMEPAGE="https://github.com/Drayux/SimpleSleep"
LICENSE="Apache-2.0 BSD MIT MPL-2.0 Unicode-3.0"

EGIT_REPO_URI="https://github.com/Drayux/SimpleSleep.git"

SLOT="0"
KEYWORDS="~amd64"
RESTRICT="strip"

RDEPEND=">=sys-libs/pam-1.3.1"
DEPEND="${RDEPEND}"
BDEPEND=""
	# virtual/pkgconfig
# ^^ complete guess on the rust version, might need tweaking

src_unpack() {
    git-r3_src_unpack
    cargo_live_src_unpack
}

# TODO: Configure not set up on SimpleSleep yet
# src_configure() {
	# cargo_src_configure --no-default-features
	# make configure \
		# --pamdir=/lib64/security \
		# --with-parentdir=/run/user \
			# || die
# }

# src_compile() {
	# cargo_src_compile
# }

src_install() {
	cargo_src_install
	fperms 4755 /usr/bin/power-state

	insinto /etc/pam.d
	doins pam.d/power-state
}
