# CONFIGURATION GENERATED BY zsh-newuser-install

HISTFILE=~/.config/zsh/zsh-history
HISTSIZE=4096
SAVEHIST=4096
setopt autocd extendedglob
unsetopt beep nomatch notify
bindkey -e

# Compinstall (supposedly handled by ohmyzsh instead)
# zstyle :compinstall filename '/home/.zshrc'
# autoload -Uz compinit
# compinit
